enum ActionTypes {
  DID_UPDATE_CODE = 'DID_UPDATE_CODE',
  DID_UPDATE_EXPRESSIONS = 'DID_UPDATE_EXPRESSIONS',
  DID_UPDATE_ERROR = 'DID_UPDATE_ERROR',
}

export const DID_UPDATE_CODE = ActionTypes.DID_UPDATE_CODE;
export const DID_UPDATE_EXPRESSIONS = ActionTypes.DID_UPDATE_EXPRESSIONS;
export const DID_UPDATE_ERROR = ActionTypes.DID_UPDATE_ERROR;
